version: "3.8"
services:
  gatsby:
    build:
      context: ./docker/gatsby
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - type: bind
        source: ./gatsby
        target: /home/node/gatsby
    user: node
    environment:
      - NODE_ENV=development
    tty: true
    stdin_open: true
