version: "3.8"
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - type: bind
        source: ./app
        target: /home/node/app
    user: node
    environment:
      - NODE_ENV=development
    tty: true
    stdin_open: true
